### ISSUE TITLE
Linux: Database is locked error

### ISSUE THREAD

**Issue by thamarnan** [SasaKaranovic/VU-Server#12] opened 2024-01-15 03:37 UTC
somehow it gets into this state
```
user@portainer:~/vudial/VU-Server$ python3 server.py 
Jan 15 2024 03:34:12.795 pid:5510 base_logger.py            62 INFO  Logging level: INFO
Jan 15 2024 03:34:12.796 pid:5510 server.py                508 INFO  Loading server config...
Jan 15 2024 03:34:12.796 pid:5510 server_config.py          19 INFO  VU1 config yaml file: /home/user/vudial/VU-Server/config.yaml
Jan 15 2024 03:34:12.796 pid:5510 database.py               17 INFO  VU1 Database file: /home/user/vudial/VU-Server/vudials.db
Jan 15 2024 03:34:17.810 pid:5510 server.py                622 ERROR Dials API service crashed during setup.
Traceback (most recent call last):
  File "/home/user/vudial/VU-Server/server.py", line 620, in main
    Dial_API_Service().run_forever()
  File "/home/user/vudial/VU-Server/server.py", line 509, in __init__
    self.config = ServerConfig('config.yaml')
  File "/home/user/vudial/VU-Server/server_config.py", line 22, in __init__
    self._load_API_keys()   # Load API keys from `api_keys` section
  File "/home/user/vudial/VU-Server/server_config.py", line 78, in _load_API_keys
    self.database.api_update_master(self.server['master_key'])
  File "/home/user/vudial/VU-Server/database.py", line 119, in api_update_master
    self._query(f"INSERT OR REPLACE INTO api_keys (key_id, key_name, key_uid, key_level) VALUES ('1', 'MASTER_KEY', '{new_key}', 99)")
  File "/home/user/vudial/VU-Server/database.py", line 193, in _query
    cursor.execute(query)
sqlite3.OperationalError: database is locked
``` 

work around for now:
```
user@portainer:~/vudial/VU-Server$ sudo fuser -k vudials.db
```

**Comment by SasaKaranovic** [comment] 2024-01-15 04:21
Hi @thamarnan ! Thank you for reporting this issue and offering a work around.

Do you have any steps on how to reproduce this issue?

**Comment by thamarnan** [comment] 2024-01-15 06:02
I couldn't reproduce any more, it was just curl different url. maybe python3 server.py end suddenly for some reason

**Comment by SasaKaranovic** [comment] 2024-02-05 03:11
Closing since at the moment there is no way of reproducing this issue.

**Closed by SasaKaranovic** 2024-02-05 03:11 UTC
